# Generated by Django 3.0.3 on 2020-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='speech_text',
            field=models.TextField(),
        ),
    ]
