# Generated by Django 3.0.3 on 2020-05-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusd_app', '0002_auto_20200508_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='speech_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emotion',
            name='speech_recording',
            field=models.FileField(upload_to='media/edusd'),
        ),
    ]
